package com.biolab.xtens.contact.bean;

import java.util.Date;

public class Data {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA.ID_DATA
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    private Integer idData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA.DESCR_DATA
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    private String descrData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA.ACQUISITION_DATE
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    private Date acquisitionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA.NOTES
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA.ID_DATA_TYPE
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    private Integer idDataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA.ID_EVT
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    private Integer idEvt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA.ID_PCOLL
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    private Integer idPcoll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA.ID_SCOLL
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    private Integer idScoll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA.ID_FCOLL
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    private Integer idFcoll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA.ID_QUALITY
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    private String idQuality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA.JSON_SCHEMA
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    private String jsonSchema;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA.ID_DATA
     *
     * @return the value of DATA.ID_DATA
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public Integer getIdData() {
        return idData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA.ID_DATA
     *
     * @param idData the value for DATA.ID_DATA
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public void setIdData(Integer idData) {
        this.idData = idData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA.DESCR_DATA
     *
     * @return the value of DATA.DESCR_DATA
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public String getDescrData() {
        return descrData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA.DESCR_DATA
     *
     * @param descrData the value for DATA.DESCR_DATA
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public void setDescrData(String descrData) {
        this.descrData = descrData == null ? null : descrData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA.ACQUISITION_DATE
     *
     * @return the value of DATA.ACQUISITION_DATE
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public Date getAcquisitionDate() {
        return acquisitionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA.ACQUISITION_DATE
     *
     * @param acquisitionDate the value for DATA.ACQUISITION_DATE
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public void setAcquisitionDate(Date acquisitionDate) {
        this.acquisitionDate = acquisitionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA.NOTES
     *
     * @return the value of DATA.NOTES
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA.NOTES
     *
     * @param notes the value for DATA.NOTES
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA.ID_DATA_TYPE
     *
     * @return the value of DATA.ID_DATA_TYPE
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public Integer getIdDataType() {
        return idDataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA.ID_DATA_TYPE
     *
     * @param idDataType the value for DATA.ID_DATA_TYPE
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public void setIdDataType(Integer idDataType) {
        this.idDataType = idDataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA.ID_EVT
     *
     * @return the value of DATA.ID_EVT
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public Integer getIdEvt() {
        return idEvt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA.ID_EVT
     *
     * @param idEvt the value for DATA.ID_EVT
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public void setIdEvt(Integer idEvt) {
        this.idEvt = idEvt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA.ID_PCOLL
     *
     * @return the value of DATA.ID_PCOLL
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public Integer getIdPcoll() {
        return idPcoll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA.ID_PCOLL
     *
     * @param idPcoll the value for DATA.ID_PCOLL
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public void setIdPcoll(Integer idPcoll) {
        this.idPcoll = idPcoll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA.ID_SCOLL
     *
     * @return the value of DATA.ID_SCOLL
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public Integer getIdScoll() {
        return idScoll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA.ID_SCOLL
     *
     * @param idScoll the value for DATA.ID_SCOLL
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public void setIdScoll(Integer idScoll) {
        this.idScoll = idScoll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA.ID_FCOLL
     *
     * @return the value of DATA.ID_FCOLL
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public Integer getIdFcoll() {
        return idFcoll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA.ID_FCOLL
     *
     * @param idFcoll the value for DATA.ID_FCOLL
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public void setIdFcoll(Integer idFcoll) {
        this.idFcoll = idFcoll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA.ID_QUALITY
     *
     * @return the value of DATA.ID_QUALITY
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public String getIdQuality() {
        return idQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA.ID_QUALITY
     *
     * @param idQuality the value for DATA.ID_QUALITY
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public void setIdQuality(String idQuality) {
        this.idQuality = idQuality == null ? null : idQuality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA.JSON_SCHEMA
     *
     * @return the value of DATA.JSON_SCHEMA
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public String getJsonSchema() {
        return jsonSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA.JSON_SCHEMA
     *
     * @param jsonSchema the value for DATA.JSON_SCHEMA
     *
     * @mbggenerated Mon May 26 12:38:56 CEST 2014
     */
    public void setJsonSchema(String jsonSchema) {
        this.jsonSchema = jsonSchema == null ? null : jsonSchema.trim();
    }
}