package com.biolab.xtens.contact.bean;

import java.util.Date;

public class PersonalData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.ID_PRS_DATA
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private Integer idPrsData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.SURNAME
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String surname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.NAME
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.ID_SEX
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String idSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.BIRTH_DATE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private Date birthDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.DECEASE_DATE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private Date deceaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.INSERT_DATE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private Date insertDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.DATE_LAST_UPDATE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private Date dateLastUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.ID_BIR_MUNICIP
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String idBirMunicip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.ID_BIR_SUBAREA
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String idBirSubarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.ID_NATIONALITY
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String idNationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.ID_CITIZENSHIP
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String idCitizenship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.ID_MARITAL_STATUS
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String idMaritalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.ID_PROFESSION
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String idProfession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.RES_CAP
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String resCap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.RES_ADDRESS
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String resAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.ID_RES_MUNICIP
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String idResMunicip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.ID_RES_SUBAREA
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String idResSubarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.DOM_ADDRESS
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String domAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.ID_DOM_MUNICIP
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String idDomMunicip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.ID_DOM_SUBAREA
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String idDomSubarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.DOM_CAP
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String domCap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.TEL1_PREF
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String tel1Pref;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.TEL1_NUM
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String tel1Num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.TEL2_PREF
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String tel2Pref;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.TEL2_NUM
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String tel2Num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.TEL3_PREF
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String tel3Pref;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.TEL3_NUM
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String tel3Num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.FAX_PREF
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String faxPref;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.FAX_NUM
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String faxNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.EMAIL
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.TAX_CODE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String taxCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.HEALTH_CODE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String healthCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.EXPIRE_HEALTH_CODE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private Date expireHealthCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.ID_EDUCATION
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String idEducation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.ID_FAMILY_DOCTOR
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private Long idFamilyDoctor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.DELETED
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.EXT_CONTACT
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String extContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.EXT_TEL_PREF
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String extTelPref;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.EXT_TEL_NUM
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String extTelNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.EXT_ADDRESS
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String extAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.CLINICAL_NOTES
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String clinicalNotes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.FIRST_VISIT
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String firstVisit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSONAL_DATA.LAST_VISIT
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    private String lastVisit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.ID_PRS_DATA
     *
     * @return the value of PERSONAL_DATA.ID_PRS_DATA
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public Integer getIdPrsData() {
        return idPrsData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.ID_PRS_DATA
     *
     * @param idPrsData the value for PERSONAL_DATA.ID_PRS_DATA
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setIdPrsData(Integer idPrsData) {
        this.idPrsData = idPrsData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.SURNAME
     *
     * @return the value of PERSONAL_DATA.SURNAME
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.SURNAME
     *
     * @param surname the value for PERSONAL_DATA.SURNAME
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setSurname(String surname) {
        this.surname = surname == null ? null : surname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.NAME
     *
     * @return the value of PERSONAL_DATA.NAME
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.NAME
     *
     * @param name the value for PERSONAL_DATA.NAME
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.ID_SEX
     *
     * @return the value of PERSONAL_DATA.ID_SEX
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getIdSex() {
        return idSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.ID_SEX
     *
     * @param idSex the value for PERSONAL_DATA.ID_SEX
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setIdSex(String idSex) {
        this.idSex = idSex == null ? null : idSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.BIRTH_DATE
     *
     * @return the value of PERSONAL_DATA.BIRTH_DATE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.BIRTH_DATE
     *
     * @param birthDate the value for PERSONAL_DATA.BIRTH_DATE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.DECEASE_DATE
     *
     * @return the value of PERSONAL_DATA.DECEASE_DATE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public Date getDeceaseDate() {
        return deceaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.DECEASE_DATE
     *
     * @param deceaseDate the value for PERSONAL_DATA.DECEASE_DATE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setDeceaseDate(Date deceaseDate) {
        this.deceaseDate = deceaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.INSERT_DATE
     *
     * @return the value of PERSONAL_DATA.INSERT_DATE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.INSERT_DATE
     *
     * @param insertDate the value for PERSONAL_DATA.INSERT_DATE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.DATE_LAST_UPDATE
     *
     * @return the value of PERSONAL_DATA.DATE_LAST_UPDATE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public Date getDateLastUpdate() {
        return dateLastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.DATE_LAST_UPDATE
     *
     * @param dateLastUpdate the value for PERSONAL_DATA.DATE_LAST_UPDATE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setDateLastUpdate(Date dateLastUpdate) {
        this.dateLastUpdate = dateLastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.ID_BIR_MUNICIP
     *
     * @return the value of PERSONAL_DATA.ID_BIR_MUNICIP
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getIdBirMunicip() {
        return idBirMunicip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.ID_BIR_MUNICIP
     *
     * @param idBirMunicip the value for PERSONAL_DATA.ID_BIR_MUNICIP
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setIdBirMunicip(String idBirMunicip) {
        this.idBirMunicip = idBirMunicip == null ? null : idBirMunicip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.ID_BIR_SUBAREA
     *
     * @return the value of PERSONAL_DATA.ID_BIR_SUBAREA
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getIdBirSubarea() {
        return idBirSubarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.ID_BIR_SUBAREA
     *
     * @param idBirSubarea the value for PERSONAL_DATA.ID_BIR_SUBAREA
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setIdBirSubarea(String idBirSubarea) {
        this.idBirSubarea = idBirSubarea == null ? null : idBirSubarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.ID_NATIONALITY
     *
     * @return the value of PERSONAL_DATA.ID_NATIONALITY
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getIdNationality() {
        return idNationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.ID_NATIONALITY
     *
     * @param idNationality the value for PERSONAL_DATA.ID_NATIONALITY
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setIdNationality(String idNationality) {
        this.idNationality = idNationality == null ? null : idNationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.ID_CITIZENSHIP
     *
     * @return the value of PERSONAL_DATA.ID_CITIZENSHIP
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getIdCitizenship() {
        return idCitizenship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.ID_CITIZENSHIP
     *
     * @param idCitizenship the value for PERSONAL_DATA.ID_CITIZENSHIP
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setIdCitizenship(String idCitizenship) {
        this.idCitizenship = idCitizenship == null ? null : idCitizenship.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.ID_MARITAL_STATUS
     *
     * @return the value of PERSONAL_DATA.ID_MARITAL_STATUS
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getIdMaritalStatus() {
        return idMaritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.ID_MARITAL_STATUS
     *
     * @param idMaritalStatus the value for PERSONAL_DATA.ID_MARITAL_STATUS
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setIdMaritalStatus(String idMaritalStatus) {
        this.idMaritalStatus = idMaritalStatus == null ? null : idMaritalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.ID_PROFESSION
     *
     * @return the value of PERSONAL_DATA.ID_PROFESSION
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getIdProfession() {
        return idProfession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.ID_PROFESSION
     *
     * @param idProfession the value for PERSONAL_DATA.ID_PROFESSION
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setIdProfession(String idProfession) {
        this.idProfession = idProfession == null ? null : idProfession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.RES_CAP
     *
     * @return the value of PERSONAL_DATA.RES_CAP
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getResCap() {
        return resCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.RES_CAP
     *
     * @param resCap the value for PERSONAL_DATA.RES_CAP
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setResCap(String resCap) {
        this.resCap = resCap == null ? null : resCap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.RES_ADDRESS
     *
     * @return the value of PERSONAL_DATA.RES_ADDRESS
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getResAddress() {
        return resAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.RES_ADDRESS
     *
     * @param resAddress the value for PERSONAL_DATA.RES_ADDRESS
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setResAddress(String resAddress) {
        this.resAddress = resAddress == null ? null : resAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.ID_RES_MUNICIP
     *
     * @return the value of PERSONAL_DATA.ID_RES_MUNICIP
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getIdResMunicip() {
        return idResMunicip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.ID_RES_MUNICIP
     *
     * @param idResMunicip the value for PERSONAL_DATA.ID_RES_MUNICIP
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setIdResMunicip(String idResMunicip) {
        this.idResMunicip = idResMunicip == null ? null : idResMunicip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.ID_RES_SUBAREA
     *
     * @return the value of PERSONAL_DATA.ID_RES_SUBAREA
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getIdResSubarea() {
        return idResSubarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.ID_RES_SUBAREA
     *
     * @param idResSubarea the value for PERSONAL_DATA.ID_RES_SUBAREA
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setIdResSubarea(String idResSubarea) {
        this.idResSubarea = idResSubarea == null ? null : idResSubarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.DOM_ADDRESS
     *
     * @return the value of PERSONAL_DATA.DOM_ADDRESS
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getDomAddress() {
        return domAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.DOM_ADDRESS
     *
     * @param domAddress the value for PERSONAL_DATA.DOM_ADDRESS
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setDomAddress(String domAddress) {
        this.domAddress = domAddress == null ? null : domAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.ID_DOM_MUNICIP
     *
     * @return the value of PERSONAL_DATA.ID_DOM_MUNICIP
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getIdDomMunicip() {
        return idDomMunicip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.ID_DOM_MUNICIP
     *
     * @param idDomMunicip the value for PERSONAL_DATA.ID_DOM_MUNICIP
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setIdDomMunicip(String idDomMunicip) {
        this.idDomMunicip = idDomMunicip == null ? null : idDomMunicip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.ID_DOM_SUBAREA
     *
     * @return the value of PERSONAL_DATA.ID_DOM_SUBAREA
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getIdDomSubarea() {
        return idDomSubarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.ID_DOM_SUBAREA
     *
     * @param idDomSubarea the value for PERSONAL_DATA.ID_DOM_SUBAREA
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setIdDomSubarea(String idDomSubarea) {
        this.idDomSubarea = idDomSubarea == null ? null : idDomSubarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.DOM_CAP
     *
     * @return the value of PERSONAL_DATA.DOM_CAP
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getDomCap() {
        return domCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.DOM_CAP
     *
     * @param domCap the value for PERSONAL_DATA.DOM_CAP
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setDomCap(String domCap) {
        this.domCap = domCap == null ? null : domCap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.TEL1_PREF
     *
     * @return the value of PERSONAL_DATA.TEL1_PREF
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getTel1Pref() {
        return tel1Pref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.TEL1_PREF
     *
     * @param tel1Pref the value for PERSONAL_DATA.TEL1_PREF
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setTel1Pref(String tel1Pref) {
        this.tel1Pref = tel1Pref == null ? null : tel1Pref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.TEL1_NUM
     *
     * @return the value of PERSONAL_DATA.TEL1_NUM
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getTel1Num() {
        return tel1Num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.TEL1_NUM
     *
     * @param tel1Num the value for PERSONAL_DATA.TEL1_NUM
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setTel1Num(String tel1Num) {
        this.tel1Num = tel1Num == null ? null : tel1Num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.TEL2_PREF
     *
     * @return the value of PERSONAL_DATA.TEL2_PREF
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getTel2Pref() {
        return tel2Pref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.TEL2_PREF
     *
     * @param tel2Pref the value for PERSONAL_DATA.TEL2_PREF
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setTel2Pref(String tel2Pref) {
        this.tel2Pref = tel2Pref == null ? null : tel2Pref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.TEL2_NUM
     *
     * @return the value of PERSONAL_DATA.TEL2_NUM
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getTel2Num() {
        return tel2Num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.TEL2_NUM
     *
     * @param tel2Num the value for PERSONAL_DATA.TEL2_NUM
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setTel2Num(String tel2Num) {
        this.tel2Num = tel2Num == null ? null : tel2Num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.TEL3_PREF
     *
     * @return the value of PERSONAL_DATA.TEL3_PREF
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getTel3Pref() {
        return tel3Pref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.TEL3_PREF
     *
     * @param tel3Pref the value for PERSONAL_DATA.TEL3_PREF
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setTel3Pref(String tel3Pref) {
        this.tel3Pref = tel3Pref == null ? null : tel3Pref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.TEL3_NUM
     *
     * @return the value of PERSONAL_DATA.TEL3_NUM
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getTel3Num() {
        return tel3Num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.TEL3_NUM
     *
     * @param tel3Num the value for PERSONAL_DATA.TEL3_NUM
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setTel3Num(String tel3Num) {
        this.tel3Num = tel3Num == null ? null : tel3Num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.FAX_PREF
     *
     * @return the value of PERSONAL_DATA.FAX_PREF
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getFaxPref() {
        return faxPref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.FAX_PREF
     *
     * @param faxPref the value for PERSONAL_DATA.FAX_PREF
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setFaxPref(String faxPref) {
        this.faxPref = faxPref == null ? null : faxPref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.FAX_NUM
     *
     * @return the value of PERSONAL_DATA.FAX_NUM
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getFaxNum() {
        return faxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.FAX_NUM
     *
     * @param faxNum the value for PERSONAL_DATA.FAX_NUM
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setFaxNum(String faxNum) {
        this.faxNum = faxNum == null ? null : faxNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.EMAIL
     *
     * @return the value of PERSONAL_DATA.EMAIL
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.EMAIL
     *
     * @param email the value for PERSONAL_DATA.EMAIL
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.TAX_CODE
     *
     * @return the value of PERSONAL_DATA.TAX_CODE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getTaxCode() {
        return taxCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.TAX_CODE
     *
     * @param taxCode the value for PERSONAL_DATA.TAX_CODE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setTaxCode(String taxCode) {
        this.taxCode = taxCode == null ? null : taxCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.HEALTH_CODE
     *
     * @return the value of PERSONAL_DATA.HEALTH_CODE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getHealthCode() {
        return healthCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.HEALTH_CODE
     *
     * @param healthCode the value for PERSONAL_DATA.HEALTH_CODE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setHealthCode(String healthCode) {
        this.healthCode = healthCode == null ? null : healthCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.EXPIRE_HEALTH_CODE
     *
     * @return the value of PERSONAL_DATA.EXPIRE_HEALTH_CODE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public Date getExpireHealthCode() {
        return expireHealthCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.EXPIRE_HEALTH_CODE
     *
     * @param expireHealthCode the value for PERSONAL_DATA.EXPIRE_HEALTH_CODE
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setExpireHealthCode(Date expireHealthCode) {
        this.expireHealthCode = expireHealthCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.ID_EDUCATION
     *
     * @return the value of PERSONAL_DATA.ID_EDUCATION
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getIdEducation() {
        return idEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.ID_EDUCATION
     *
     * @param idEducation the value for PERSONAL_DATA.ID_EDUCATION
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setIdEducation(String idEducation) {
        this.idEducation = idEducation == null ? null : idEducation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.ID_FAMILY_DOCTOR
     *
     * @return the value of PERSONAL_DATA.ID_FAMILY_DOCTOR
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public Long getIdFamilyDoctor() {
        return idFamilyDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.ID_FAMILY_DOCTOR
     *
     * @param idFamilyDoctor the value for PERSONAL_DATA.ID_FAMILY_DOCTOR
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setIdFamilyDoctor(Long idFamilyDoctor) {
        this.idFamilyDoctor = idFamilyDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.DELETED
     *
     * @return the value of PERSONAL_DATA.DELETED
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.DELETED
     *
     * @param deleted the value for PERSONAL_DATA.DELETED
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.EXT_CONTACT
     *
     * @return the value of PERSONAL_DATA.EXT_CONTACT
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getExtContact() {
        return extContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.EXT_CONTACT
     *
     * @param extContact the value for PERSONAL_DATA.EXT_CONTACT
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setExtContact(String extContact) {
        this.extContact = extContact == null ? null : extContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.EXT_TEL_PREF
     *
     * @return the value of PERSONAL_DATA.EXT_TEL_PREF
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getExtTelPref() {
        return extTelPref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.EXT_TEL_PREF
     *
     * @param extTelPref the value for PERSONAL_DATA.EXT_TEL_PREF
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setExtTelPref(String extTelPref) {
        this.extTelPref = extTelPref == null ? null : extTelPref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.EXT_TEL_NUM
     *
     * @return the value of PERSONAL_DATA.EXT_TEL_NUM
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getExtTelNum() {
        return extTelNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.EXT_TEL_NUM
     *
     * @param extTelNum the value for PERSONAL_DATA.EXT_TEL_NUM
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setExtTelNum(String extTelNum) {
        this.extTelNum = extTelNum == null ? null : extTelNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.EXT_ADDRESS
     *
     * @return the value of PERSONAL_DATA.EXT_ADDRESS
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getExtAddress() {
        return extAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.EXT_ADDRESS
     *
     * @param extAddress the value for PERSONAL_DATA.EXT_ADDRESS
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setExtAddress(String extAddress) {
        this.extAddress = extAddress == null ? null : extAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.CLINICAL_NOTES
     *
     * @return the value of PERSONAL_DATA.CLINICAL_NOTES
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getClinicalNotes() {
        return clinicalNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.CLINICAL_NOTES
     *
     * @param clinicalNotes the value for PERSONAL_DATA.CLINICAL_NOTES
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setClinicalNotes(String clinicalNotes) {
        this.clinicalNotes = clinicalNotes == null ? null : clinicalNotes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.FIRST_VISIT
     *
     * @return the value of PERSONAL_DATA.FIRST_VISIT
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getFirstVisit() {
        return firstVisit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.FIRST_VISIT
     *
     * @param firstVisit the value for PERSONAL_DATA.FIRST_VISIT
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setFirstVisit(String firstVisit) {
        this.firstVisit = firstVisit == null ? null : firstVisit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSONAL_DATA.LAST_VISIT
     *
     * @return the value of PERSONAL_DATA.LAST_VISIT
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public String getLastVisit() {
        return lastVisit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSONAL_DATA.LAST_VISIT
     *
     * @param lastVisit the value for PERSONAL_DATA.LAST_VISIT
     *
     * @mbggenerated Sun Apr 14 16:24:57 CEST 2013
     */
    public void setLastVisit(String lastVisit) {
        this.lastVisit = lastVisit == null ? null : lastVisit.trim();
    }
}
